AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal POSIX shell custom runtime layer for provided.al2023 (arm64, x86_64).

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-shell-runtime
    Description: Minimal POSIX shell custom runtime layer for provided.al2023 (arm64, x86_64) including AWS CLI v2 and jq.
    Author: Maxim Parkachov
    HomePageUrl: https://github.com/mparkachov/lambda-shell-runtime
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: SAR_README.md
    Labels: [lambda, runtime, layer, shell, provided-al2023, arm64, x86_64, awscli]
    SemanticVersion: 2.32.26

Resources:
  RuntimeArm64Application:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:541185764973:applications/lambda-shell-runtime-arm64
        SemanticVersion: 2.32.26

  RuntimeAmd64Application:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:541185764973:applications/lambda-shell-runtime-amd64
        SemanticVersion: 2.32.26

Outputs:
  LayerVersionArnArm64:
    Description: ARN of the published Lambda layer version (arm64).
    Value: !GetAtt RuntimeArm64Application.Outputs.LayerVersionArn
  LayerVersionArnAmd64:
    Description: ARN of the published Lambda layer version (x86_64).
    Value: !GetAtt RuntimeAmd64Application.Outputs.LayerVersionArn
