#!/bin/sh
set -eu

LSR_AWS_REGION=${LSR_AWS_REGION:-us-east-1}
export AWS_REGION="$LSR_AWS_REGION"
export AWS_DEFAULT_REGION="$LSR_AWS_REGION"

LSR_BUCKET_NAME=${LSR_BUCKET_NAME:-lambda-shell-runtime}
LSR_BUCKET_NAME_DEV=${LSR_BUCKET_NAME_DEV:-lambda-shell-runtime-dev}
LSR_STACK_NAME=${LSR_STACK_NAME:-lambda-shell-runtime-setup}
LSR_STACK_NAME_DEV=${LSR_STACK_NAME_DEV:-lambda-shell-runtime-dev-setup}
LSR_SAR_APP_BASE=${LSR_SAR_APP_BASE:-${LSR_SAR_APP_NAME:-lambda-shell-runtime}}
LSR_SAR_APP_NAME_ARM64=${LSR_SAR_APP_NAME_ARM64:-${LSR_SAR_APP_BASE}-arm64}
LSR_SAR_APP_NAME_AMD64=${LSR_SAR_APP_NAME_AMD64:-${LSR_SAR_APP_BASE}-amd64}
LSR_S3_PREFIX=${LSR_S3_PREFIX:-sar}

S3_BUCKET=${S3_BUCKET:-$LSR_BUCKET_NAME}
export S3_BUCKET
