#!/bin/sh
set -eu

LSR_AWS_REGION=${LSR_AWS_REGION:-us-east-1}
export AWS_REGION="$LSR_AWS_REGION"
export AWS_DEFAULT_REGION="$LSR_AWS_REGION"

LSR_ENV=${ENV:-prod}
case "$LSR_ENV" in
  prod|dev) ;;
  *)
    printf '%s\n' "ENV must be 'prod' or 'dev' (got: $LSR_ENV)" >&2
    exit 1
    ;;
esac

LSR_SAR_APP_BASE_PROD=${LSR_SAR_APP_BASE:-${LSR_SAR_APP_NAME:-lambda-shell-runtime}}
LSR_SAR_APP_BASE_DEV=${LSR_SAR_APP_BASE_DEV:-lambda-shell-runtime-dev}

LSR_BUCKET_NAME_PROD=${LSR_BUCKET_NAME:-lambda-shell-runtime}
LSR_BUCKET_NAME_DEV=${LSR_BUCKET_NAME_DEV:-lambda-shell-runtime-dev}

LSR_STACK_NAME_PROD=${LSR_STACK_NAME:-lambda-shell-runtime-setup}
LSR_STACK_NAME_DEV=${LSR_STACK_NAME_DEV:-lambda-shell-runtime-dev-setup}

LSR_S3_PREFIX=${LSR_S3_PREFIX:-sar}
LSR_SAR_VERSION_DEV=${LSR_SAR_VERSION_DEV:-0.0.0}

if [ "$LSR_ENV" = "dev" ]; then
  LSR_BUCKET_NAME=$LSR_BUCKET_NAME_DEV
  LSR_STACK_NAME=$LSR_STACK_NAME_DEV
  LSR_SAR_APP_BASE=$LSR_SAR_APP_BASE_DEV
  LSR_SAR_VERSION=${LSR_SAR_VERSION:-$LSR_SAR_VERSION_DEV}
else
  LSR_BUCKET_NAME=$LSR_BUCKET_NAME_PROD
  LSR_STACK_NAME=$LSR_STACK_NAME_PROD
  LSR_SAR_APP_BASE=$LSR_SAR_APP_BASE_PROD
  LSR_SAR_VERSION=${LSR_SAR_VERSION:-}
fi

LSR_SAR_APP_NAME_ARM64=${LSR_SAR_APP_NAME_ARM64:-${LSR_SAR_APP_BASE}-arm64}
LSR_SAR_APP_NAME_AMD64=${LSR_SAR_APP_NAME_AMD64:-${LSR_SAR_APP_BASE}-amd64}
LSR_SAR_APP_NAME_WRAPPER=${LSR_SAR_APP_NAME_WRAPPER:-$LSR_SAR_APP_BASE}

LSR_LAYER_NAME_ARM64=${LSR_LAYER_NAME_ARM64:-$LSR_SAR_APP_NAME_ARM64}
LSR_LAYER_NAME_AMD64=${LSR_LAYER_NAME_AMD64:-$LSR_SAR_APP_NAME_AMD64}

LSR_SAR_STACK_NAME_ARM64=${LSR_SAR_STACK_NAME_ARM64:-$LSR_SAR_APP_NAME_ARM64}
LSR_SAR_STACK_NAME_AMD64=${LSR_SAR_STACK_NAME_AMD64:-$LSR_SAR_APP_NAME_AMD64}

S3_BUCKET=${S3_BUCKET:-$LSR_BUCKET_NAME}
export S3_BUCKET
